// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: store/metadb/envelope.proto

package metadb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Closed set of content types to prevent drift
type ContentType int32

const (
	ContentType_CONTENT_TYPE_UNSPECIFIED  ContentType = 0
	ContentType_CONTENT_TYPE_JSON         ContentType = 1 // application/json
	ContentType_CONTENT_TYPE_XML          ContentType = 2 // application/xml
	ContentType_CONTENT_TYPE_TEXT         ContentType = 3 // text/plain
	ContentType_CONTENT_TYPE_OCTET_STREAM ContentType = 4 // application/octet-stream
)

// Enum value maps for ContentType.
var (
	ContentType_name = map[int32]string{
		0: "CONTENT_TYPE_UNSPECIFIED",
		1: "CONTENT_TYPE_JSON",
		2: "CONTENT_TYPE_XML",
		3: "CONTENT_TYPE_TEXT",
		4: "CONTENT_TYPE_OCTET_STREAM",
	}
	ContentType_value = map[string]int32{
		"CONTENT_TYPE_UNSPECIFIED":  0,
		"CONTENT_TYPE_JSON":         1,
		"CONTENT_TYPE_XML":          2,
		"CONTENT_TYPE_TEXT":         3,
		"CONTENT_TYPE_OCTET_STREAM": 4,
	}
)

func (x ContentType) Enum() *ContentType {
	p := new(ContentType)
	*p = x
	return p
}

func (x ContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_store_metadb_envelope_proto_enumTypes[0].Descriptor()
}

func (ContentType) Type() protoreflect.EnumType {
	return &file_store_metadb_envelope_proto_enumTypes[0]
}

func (x ContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentType.Descriptor instead.
func (ContentType) EnumDescriptor() ([]byte, []int) {
	return file_store_metadb_envelope_proto_rawDescGZIP(), []int{0}
}

// Closed set of encodings
type ContentEncoding int32

const (
	ContentEncoding_CONTENT_ENCODING_IDENTITY ContentEncoding = 0 // no compression
	ContentEncoding_CONTENT_ENCODING_ZSTD     ContentEncoding = 1 // zstandard compression
)

// Enum value maps for ContentEncoding.
var (
	ContentEncoding_name = map[int32]string{
		0: "CONTENT_ENCODING_IDENTITY",
		1: "CONTENT_ENCODING_ZSTD",
	}
	ContentEncoding_value = map[string]int32{
		"CONTENT_ENCODING_IDENTITY": 0,
		"CONTENT_ENCODING_ZSTD":     1,
	}
)

func (x ContentEncoding) Enum() *ContentEncoding {
	p := new(ContentEncoding)
	*p = x
	return p
}

func (x ContentEncoding) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ContentEncoding) Descriptor() protoreflect.EnumDescriptor {
	return file_store_metadb_envelope_proto_enumTypes[1].Descriptor()
}

func (ContentEncoding) Type() protoreflect.EnumType {
	return &file_store_metadb_envelope_proto_enumTypes[1]
}

func (x ContentEncoding) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ContentEncoding.Descriptor instead.
func (ContentEncoding) EnumDescriptor() ([]byte, []int) {
	return file_store_metadb_envelope_proto_rawDescGZIP(), []int{1}
}

// MetadataEnvelope wraps all stored metadata with cache control and integrity fields.
// Note: The storage key (protocol + kind + key) is NOT stored in the envelope.
// It is passed explicitly to APIs and used as the BoltDB key.
type MetadataEnvelope struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Schema version for future evolution (start at 1)
	EnvelopeVersion uint32 `protobuf:"varint,1,opt,name=envelope_version,json=envelopeVersion,proto3" json:"envelope_version,omitempty"`
	// Payload description
	ContentType     ContentType     `protobuf:"varint,2,opt,name=content_type,json=contentType,proto3,enum=metadb.v1.ContentType" json:"content_type,omitempty"`
	ContentEncoding ContentEncoding `protobuf:"varint,3,opt,name=content_encoding,json=contentEncoding,proto3,enum=metadb.v1.ContentEncoding" json:"content_encoding,omitempty"`
	Payload         []byte          `protobuf:"bytes,4,opt,name=payload,proto3" json:"payload,omitempty"` // raw or compressed bytes
	// Integrity (of decoded payload)
	PayloadDigest string `protobuf:"bytes,5,opt,name=payload_digest,json=payloadDigest,proto3" json:"payload_digest,omitempty"` // "sha256:<hex>" of uncompressed bytes (canonical format)
	PayloadSize   uint64 `protobuf:"varint,6,opt,name=payload_size,json=payloadSize,proto3" json:"payload_size,omitempty"`      // uncompressed size in bytes
	// Cache control
	FetchedAtUnixMs    int64  `protobuf:"varint,10,opt,name=fetched_at_unix_ms,json=fetchedAtUnixMs,proto3" json:"fetched_at_unix_ms,omitempty"`
	ExpiresAtUnixMs    int64  `protobuf:"varint,11,opt,name=expires_at_unix_ms,json=expiresAtUnixMs,proto3" json:"expires_at_unix_ms,omitempty"` // 0 = no expiry
	TtlSeconds         int64  `protobuf:"varint,12,opt,name=ttl_seconds,json=ttlSeconds,proto3" json:"ttl_seconds,omitempty"`                    // original TTL (for debugging/revalidation)
	Etag               string `protobuf:"bytes,13,opt,name=etag,proto3" json:"etag,omitempty"`
	LastModifiedUnixMs int64  `protobuf:"varint,14,opt,name=last_modified_unix_ms,json=lastModifiedUnixMs,proto3" json:"last_modified_unix_ms,omitempty"`
	// Provenance
	Upstream       string `protobuf:"bytes,15,opt,name=upstream,proto3" json:"upstream,omitempty"`                                    // upstream registry host (no secrets, no full URLs)
	UpstreamStatus uint32 `protobuf:"varint,16,opt,name=upstream_status,json=upstreamStatus,proto3" json:"upstream_status,omitempty"` // HTTP status from upstream (200, 404, 5xx, etc.)
	// Blob references (hashes of cached artifacts this metadata refers to)
	// Must be deduplicated and in canonical format: "sha256:<hex>" or "blake3:<hex>"
	BlobRefs []string `protobuf:"bytes,20,rep,name=blob_refs,json=blobRefs,proto3" json:"blob_refs,omitempty"`
	// Extensibility escape hatch (use sparingly)
	// Max 10 keys, max 1KB total size enforced at write time
	Attributes    map[string][]byte `protobuf:"bytes,30,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetadataEnvelope) Reset() {
	*x = MetadataEnvelope{}
	mi := &file_store_metadb_envelope_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetadataEnvelope) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetadataEnvelope) ProtoMessage() {}

func (x *MetadataEnvelope) ProtoReflect() protoreflect.Message {
	mi := &file_store_metadb_envelope_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetadataEnvelope.ProtoReflect.Descriptor instead.
func (*MetadataEnvelope) Descriptor() ([]byte, []int) {
	return file_store_metadb_envelope_proto_rawDescGZIP(), []int{0}
}

func (x *MetadataEnvelope) GetEnvelopeVersion() uint32 {
	if x != nil {
		return x.EnvelopeVersion
	}
	return 0
}

func (x *MetadataEnvelope) GetContentType() ContentType {
	if x != nil {
		return x.ContentType
	}
	return ContentType_CONTENT_TYPE_UNSPECIFIED
}

func (x *MetadataEnvelope) GetContentEncoding() ContentEncoding {
	if x != nil {
		return x.ContentEncoding
	}
	return ContentEncoding_CONTENT_ENCODING_IDENTITY
}

func (x *MetadataEnvelope) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *MetadataEnvelope) GetPayloadDigest() string {
	if x != nil {
		return x.PayloadDigest
	}
	return ""
}

func (x *MetadataEnvelope) GetPayloadSize() uint64 {
	if x != nil {
		return x.PayloadSize
	}
	return 0
}

func (x *MetadataEnvelope) GetFetchedAtUnixMs() int64 {
	if x != nil {
		return x.FetchedAtUnixMs
	}
	return 0
}

func (x *MetadataEnvelope) GetExpiresAtUnixMs() int64 {
	if x != nil {
		return x.ExpiresAtUnixMs
	}
	return 0
}

func (x *MetadataEnvelope) GetTtlSeconds() int64 {
	if x != nil {
		return x.TtlSeconds
	}
	return 0
}

func (x *MetadataEnvelope) GetEtag() string {
	if x != nil {
		return x.Etag
	}
	return ""
}

func (x *MetadataEnvelope) GetLastModifiedUnixMs() int64 {
	if x != nil {
		return x.LastModifiedUnixMs
	}
	return 0
}

func (x *MetadataEnvelope) GetUpstream() string {
	if x != nil {
		return x.Upstream
	}
	return ""
}

func (x *MetadataEnvelope) GetUpstreamStatus() uint32 {
	if x != nil {
		return x.UpstreamStatus
	}
	return 0
}

func (x *MetadataEnvelope) GetBlobRefs() []string {
	if x != nil {
		return x.BlobRefs
	}
	return nil
}

func (x *MetadataEnvelope) GetAttributes() map[string][]byte {
	if x != nil {
		return x.Attributes
	}
	return nil
}

var File_store_metadb_envelope_proto protoreflect.FileDescriptor

const file_store_metadb_envelope_proto_rawDesc = "" +
	"\n" +
	"\x1bstore/metadb/envelope.proto\x12\tmetadb.v1\"\xd3\x05\n" +
	"\x10MetadataEnvelope\x12)\n" +
	"\x10envelope_version\x18\x01 \x01(\rR\x0fenvelopeVersion\x129\n" +
	"\fcontent_type\x18\x02 \x01(\x0e2\x16.metadb.v1.ContentTypeR\vcontentType\x12E\n" +
	"\x10content_encoding\x18\x03 \x01(\x0e2\x1a.metadb.v1.ContentEncodingR\x0fcontentEncoding\x12\x18\n" +
	"\apayload\x18\x04 \x01(\fR\apayload\x12%\n" +
	"\x0epayload_digest\x18\x05 \x01(\tR\rpayloadDigest\x12!\n" +
	"\fpayload_size\x18\x06 \x01(\x04R\vpayloadSize\x12+\n" +
	"\x12fetched_at_unix_ms\x18\n" +
	" \x01(\x03R\x0ffetchedAtUnixMs\x12+\n" +
	"\x12expires_at_unix_ms\x18\v \x01(\x03R\x0fexpiresAtUnixMs\x12\x1f\n" +
	"\vttl_seconds\x18\f \x01(\x03R\n" +
	"ttlSeconds\x12\x12\n" +
	"\x04etag\x18\r \x01(\tR\x04etag\x121\n" +
	"\x15last_modified_unix_ms\x18\x0e \x01(\x03R\x12lastModifiedUnixMs\x12\x1a\n" +
	"\bupstream\x18\x0f \x01(\tR\bupstream\x12'\n" +
	"\x0fupstream_status\x18\x10 \x01(\rR\x0eupstreamStatus\x12\x1b\n" +
	"\tblob_refs\x18\x14 \x03(\tR\bblobRefs\x12K\n" +
	"\n" +
	"attributes\x18\x1e \x03(\v2+.metadb.v1.MetadataEnvelope.AttributesEntryR\n" +
	"attributes\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\fR\x05value:\x028\x01*\x8e\x01\n" +
	"\vContentType\x12\x1c\n" +
	"\x18CONTENT_TYPE_UNSPECIFIED\x10\x00\x12\x15\n" +
	"\x11CONTENT_TYPE_JSON\x10\x01\x12\x14\n" +
	"\x10CONTENT_TYPE_XML\x10\x02\x12\x15\n" +
	"\x11CONTENT_TYPE_TEXT\x10\x03\x12\x1d\n" +
	"\x19CONTENT_TYPE_OCTET_STREAM\x10\x04*K\n" +
	"\x0fContentEncoding\x12\x1d\n" +
	"\x19CONTENT_ENCODING_IDENTITY\x10\x00\x12\x19\n" +
	"\x15CONTENT_ENCODING_ZSTD\x10\x01B1Z/github.com/wolfeidau/content-cache/store/metadbb\x06proto3"

var (
	file_store_metadb_envelope_proto_rawDescOnce sync.Once
	file_store_metadb_envelope_proto_rawDescData []byte
)

func file_store_metadb_envelope_proto_rawDescGZIP() []byte {
	file_store_metadb_envelope_proto_rawDescOnce.Do(func() {
		file_store_metadb_envelope_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_store_metadb_envelope_proto_rawDesc), len(file_store_metadb_envelope_proto_rawDesc)))
	})
	return file_store_metadb_envelope_proto_rawDescData
}

var file_store_metadb_envelope_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_store_metadb_envelope_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_store_metadb_envelope_proto_goTypes = []any{
	(ContentType)(0),         // 0: metadb.v1.ContentType
	(ContentEncoding)(0),     // 1: metadb.v1.ContentEncoding
	(*MetadataEnvelope)(nil), // 2: metadb.v1.MetadataEnvelope
	nil,                      // 3: metadb.v1.MetadataEnvelope.AttributesEntry
}
var file_store_metadb_envelope_proto_depIdxs = []int32{
	0, // 0: metadb.v1.MetadataEnvelope.content_type:type_name -> metadb.v1.ContentType
	1, // 1: metadb.v1.MetadataEnvelope.content_encoding:type_name -> metadb.v1.ContentEncoding
	3, // 2: metadb.v1.MetadataEnvelope.attributes:type_name -> metadb.v1.MetadataEnvelope.AttributesEntry
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_store_metadb_envelope_proto_init() }
func file_store_metadb_envelope_proto_init() {
	if File_store_metadb_envelope_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_store_metadb_envelope_proto_rawDesc), len(file_store_metadb_envelope_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_store_metadb_envelope_proto_goTypes,
		DependencyIndexes: file_store_metadb_envelope_proto_depIdxs,
		EnumInfos:         file_store_metadb_envelope_proto_enumTypes,
		MessageInfos:      file_store_metadb_envelope_proto_msgTypes,
	}.Build()
	File_store_metadb_envelope_proto = out.File
	file_store_metadb_envelope_proto_goTypes = nil
	file_store_metadb_envelope_proto_depIdxs = nil
}
